name: set-version
on:
  push:
    branches:
      - main
jobs:
  compile:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v2
          
      - name: Get Version
        id: get-version
        run: echo "::set-output name=version::$(cat beamertheme*.sty | python .github/scripts/compute-version.py)"
        
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get-version.outputs.version }}'
